# Generated by Django 3.2 on 2021-05-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0002_alter_userdata_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
