# Generated by Django 3.2 on 2021-05-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0003_auto_20210520_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='email',
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
    ]
